// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using AssemblyCSharp;
using System;
//namespace AssemblyCSharp
//{
	public class UserInfo
	{
		public string Name{set;get;}
		public int Age{set;get;}
		public int UserID{set;get;}

        public string Server { get; set; }

        public int Order { get; set; }
        public int Troop { get; set; }
        public string ViewId { get; set; }
        public HeroInfo Hero { get; set; }

		public UserInfo ()
		{
		}

        private static UserInfo defaultUser = null;
        public static UserInfo DefaultUser
        {
            get {
                if (defaultUser == null)
                    defaultUser = new UserInfo();
                return defaultUser;
            }
        }

		public override string ToString ()
		{
			return LPC_XMLTool.Serializer(typeof(UserInfo),this);
		}

    }
//}

